#Size of the screen 
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#Size of the player
PLAYER_RADIUS = 20
LINE_WIDTH = 2 

#Movement Variables
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200


#Asteroid Variables
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#Shot Variables
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3